#
# Deployment
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: hello
  replicas: 5
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: hello
          image: gcr.io/google-samples/hello-app:2.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
#
# Service
#
apiVersion: v1
kind: Service
metadata:
  name: hello-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: hello
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8080
---
#
# Ingress
#
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/load-balance: "least_conn"  # default: "round_robin"
    nginx.ingress.kubernetes.io/affinity: "none"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /*
            pathType: ImplementationSpecific # Prefix
            backend:
              service:
                name: hello-service
                port:
                  number: 8081