apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hello-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hello-deployment
  minReplicas: 1
  maxReplicas: 20
  targetCPUUtilizationPercentage: 10